config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :enrollments
  resources :participants
  resources :coordinators do
    get :export_csv, on: :member
  end
  resources :registries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/coordinator.rb
# frozen_string_literal: true

# app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_many :enrollments
  has_many :registries, through: :enrollments
  has_many :participants, through: :enrollments
end

app/controllers/coordinators_controller.rb
# frozen_string_literal: true

class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: %i[show edit update destroy export_csv]

  def index
    @coordinators = Coordinator.all
  end

  def show
    @participants = @coordinator.participants
    @count_by_birth_year = @coordinator.participants.group(:date_of_birth).count
    @count_by_gender = @coordinator.participants.group(:gender).count
  end

  def export_csv
    @participants = @coordinator.participants
    respond_to do |format|
      format.csv { send_data @participants.to_csv }
    end
  end

  def new
    @coordinator = Coordinator.new
  end

  def edit; end

  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: 'Coordinator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_coordinator
    @coordinator = Coordinator.find(params[:id])
  end

  def coordinator_params
    params.require(:coordinator).permit(:email, :name, :phone_number)
  end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_form.html.erb
<%= form_with(model: coordinator, local: true) do |form| %>
  <% if coordinator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
      <% coordinator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Show', @coordinator %> |
<%= link_to 'Back', coordinators_path %>

app/views/coordinators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coordinators</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinators.each do |coordinator| %>
      <tr>
        <td><%= coordinator.email %></td>
        <td><%= coordinator.name %></td>
        <td><%= coordinator.phone_number %></td>
        <td><%= link_to 'Show', coordinator %></td>
        <td><%= link_to 'Edit', edit_coordinator_path(coordinator) %></td>
        <td><%= link_to 'Destroy', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordinator', new_coordinator_path %>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Back', coordinators_path %>

app/views/coordinators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @coordinator.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coordinator.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @coordinator.phone_number %>
</p>

<%= link_to 'Edit', edit_coordinator_path(@coordinator) %> |
<%= link_to 'Back', coordinators_path %>

<h3>All participants</h3>
<ul>
  <% @participants.each do |participant| %>
    <li><%= participant.name %></li>
  <% end %>
</ul>

<h3>participant Count Aggrgate by birth year</h3>
<% @count_by_birth_year.each do |key,value| -%>
<%= key.year %>=<%= value %>
<% end %>


<h3>participant Count Aggrgate by gender</h3>
<% @count_by_gender.each do |key,value| -%>
<%= key %>=<%= value %>
<% end %>


<br>
<%= link_to 'export all participant to csv', export_csv_coordinator_path(id: @coordinator.id, format: "csv") %>