config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :enrollments
  resources :participants
  resources :coordinators do
    get :export_csv, on: :member
  end
  resources :registries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/registry.rb
# frozen_string_literal: true

# app/models/registry.rb
class Registry < ApplicationRecord
  has_many :enrollments
  has_many :coordinators, through: :enrollments
  has_many :participants, through: :enrollments

  enum state: %i[open closed]
  STATUS = %w[open closed].freeze
end

app/controllers/registries_controller.rb
# frozen_string_literal: true

# app/controller/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: %i[show edit update destroy]

  def index
    @registries = Registry.all
  end

  def show
    @participants = @registry.participants
  end

  def new
    @registry = Registry.new
  end

  def edit; end

  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_registry
    @registry = Registry.find(params[:id])
  end

  def registry_params
    params.require(:registry).permit(:name, :location, :state)
  end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= form_with(model: registry, local: true) do |form| %>
  <% if registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
      <% registry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, options_for_select(Registry::STATUS), prompt: 'Select State' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Editing Registry</h1>

<%= render 'form', registry: @registry %>

<%= link_to 'Show', @registry %> |
<%= link_to 'Back', registries_path %>

app/views/registries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registries.each do |registry| %>
      <tr>
        <td><%= registry.name %></td>
        <td><%= registry.location %></td>
        <td><%= registry.state %></td>
        <td><%= link_to 'Show', registry %></td>
        <td><%= link_to 'Edit', edit_registry_path(registry) %></td>
        <td><%= link_to 'Destroy', registry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registry', new_registry_path %>

app/views/registries/new.html.erb
<h1>New Registry</h1>

<%= render 'form', registry: @registry %>

<%= link_to 'Back', registries_path %>

app/views/registries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registry.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @registry.location %>
</p>

<p>
  <strong>State:</strong>
  <%= @registry.state %>
</p>

<%= link_to 'Edit', edit_registry_path(@registry) %> |
<%= link_to 'Back', registries_path %>


<h3>Participants<h3>
<ul>
  <% @participants.each do |participant| %>
    <li><%= participant.name %></li>
  <% end %>
<ul>