config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :enrollments
  resources :participants
  resources :coordinators do
    get :export_csv, on: :member
  end
  resources :registries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/enrollment.rb
# frozen_string_literal: true

# app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :registry
  belongs_to :coordinator
  belongs_to :participant

  validates :participant_id,
            uniqueness: { scope: :registry_id,
                          message: 'Cannot be enrolled on a same registry more than once'}
end

app/controllers/enrollments_controller.rb
# frozen_string_literal: true

class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]

  def index
    @enrollments = Enrollment.all
  end

  def show; end

  def new
    @enrollment = Enrollment.new
  end

  def edit; end

  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:registry_id, :coordinator_id,
                                       :participant_id, :remarks)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :registry_id %>
    <%= form.select :registry_id, options_for_select(Registry.where(state: 0).map{ |s| [s.name, s.id] }), prompt: 'Select registry' %>
  </div>

  <div class="field">
    <%= form.label :coordinator_id %>
    <%= form.select :coordinator_id, options_for_select(Coordinator.all.map{ |s| [s.email, s.id] }), prompt: 'Select coordinator' %>
  </div>

  <div class="field">
    <%= form.label :participant_id %>
    <%= form.select :participant_id, options_for_select(Participant.all.map{|s|[s.name, s.id] }), prompt: 'Select participant' %>
  </div>

<div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Registry</th>
      <th>Coordinator</th>
      <th>Participant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.registry&.name %></td>
        <td><%= enrollment.coordinator&.email %></td>
        <td><%= enrollment.participant&.name %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registry:</strong>
  <%= @enrollment.registry&.name %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @enrollment.coordinator&.email %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @enrollment.participant&.name %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @enrollment.remarks %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>